### ISSUE TITLE
Prepare Poster

### ISSUE THREAD

**Issue by SigmundGranaas** [aclgen/aclgen#42]
## Poster
Create a poster and a presentation which will be used to present our thesis to other Bachelor students. The presentation will form the base for a discussion regarding our project, and should be used to discover potential flaws and shortcoming of our projects. 

### Requirements
- [x] Deliver a poster and a presentation by Monday 28th of march, 08:15
- [x] Document who this project is for, and what is trying to be accomplished
- [x] Document which knowledge we need, and how we are systematically gathering this knowledge
- [x] What have we learned regarding the final thesis thus far, and what would we like share with the others

### TODO
- [x] Create a mock of the poster
- [x] Outline the presentation points by highlighting the core aspect of our presentation
- [x] Document which methods we are supposedly using
- [x] Create a script for the presentation
- [x] Refine the poster with graphics and styles

---

#### Introduction - What are we doing
ACLGen is a development project initiated by Sikt, formelrly known as Uninett. The goal of the project is to develop a solution for creating and managing Access Control Lists. Sikt already has a solution for managing these rules, called FireWallBuilder, but the software is old, hard to access, hard to use, even harder to use right and lacks the capability to be integrated into newer solutions and initiatives from Sikt, like Campus Network As A Service. 

#### Who are Sikt? 
Most student depends on the work from Sikt everyday. Sikt is responsible for the Internet infrastructure provided to all universities in Norway. Most of you know them from using the network eduroam during your day-to-day studies, but they do a lot more than just offering free wifi. 

#### What are Access control lists?
Most people interested in technology has heard about a firewall, it keeps the bad stuff out of your PC or network, and allows essential traffic to pass. An essential part of the firewall operates using predefined rules for what type of traffic is allowed, as well as where this traffic is permitted to origin from. 

By creating long lists of which types of traffic is permitted, which is blocked, and which is limited to some specifications, you can effectively control which type of access devices and people have to the network. The lists are called access control lists, effectively creating and managing these lists is the general goal of this project.

#### Middle - what is being done - and how are we doing it
The goal of the project is very open, there is no "one" solution imaged. There are very few hard requirements imposed by Sikt. They wanted a better solution for managing these rules, we have committed to research and develop it.

#### Digital infrastructure is complex
Digital infrastructure is complex, and can be hard to understand. We are no experts in the field, and know we have a lot of learning to do before we can take meaningful decisions regarding the project and its scope. It was therefore needed to figure out what we didn't know, as well as what we didn't know we actually knew about this project.

#### Things we needed to figure out:
- Accessing and using FirewallBuilder is hard, how can it be improved?
- How can rules be created without a direct dependency on a physical hardware vendor?
- How should a modern interpretation look?
- How should access to this service be managed - controlled - accessed
- Would it be valuable to integrate this tool into their existing toolbox?
- Is it possible to create a useful tool in this timeframe?

#### Project stages

We decided to split this project into two parts, research and development.

The research stage was dedicated to researching and prototyping, while the development phase would be dedicated to developing the solution. The R&D phase would run for as long as we had to active courses, which means we could focus all of our time and energy on development when we were done with our exam.

#### Testing: prototype to learn
Our primary method of gathering information during the first period was researching a topic, and then creating a prototype to test our understanding or assumption of the topic. 

#### UI example
An example of this is how the design for the initial UI was made. First we gathered information on existing or similar solutions. This would be existing firewall solutions as well as the application Sikt is currently using to manage infrastrukture. A prototype was created based on this, and tested by letting the network engineers over at Sikt scrutinize it. These are after all the primary users of this application, and their feedback is most valuable we can get.

 This process allows us to check if we actually understood the problems of the old application, and to see if we can come up with new solutions. They had a lot of small suggestions to how the design would be better for them, and was taken into account for the next time they are going test it, which is this friday, and every other week until we deliver our project. 

#### Second project phase
The second phase of this project is the development phase, which we have just started. In the spirit of continually testing what we are doing, we decided to base our development around scrum. This would allow us to focus on small, time-boxed iterations where we could present our work to the team of engineers at Sikt, and they would be able to to test our application. 

#### sprints
Our sprints are two weeks long and has a one primary goal. This first sprint is will focus on creating simple rules for small networks using our technology stack. The results of this sprint will tell us if we had a good enough understanding of the technologies and concepts needed to fulfill this task.

The next sprint will hopefully focus on more advances networking scenarios like subnetting and dealing with more network devices, however, this goal will have to change if the first sprint does not go as planned.

#### End -  what has been accomplished thus far, and what have we learned.

designs are developed and frameworks have been chosen. 
Basic scenarios has been tested to test our understanding of the underlying technologies.
We have created prototypes which have given us a solid foundation to start our sprints with.

Our framework thus far consists of a web-application based on react and next.js, with a Django backend which uses a tool called Capirka developed by Google to generate Access Control Lists for any router vendor.

Notes:
Working from home did not work very well
Network infrastructure is hard

### Estimates
- Preparation: 6 + 7,5 
- Presentation: 7,5 hours

### Actual time spent
10:30 - 15:30 Sigmund - 30min - 1.5h = 3hr starting creating poster
10:30 - 13.30 = 3hr finishing poster

**Comment by SigmundGranaas** [comment]
General questions for the next groups:
- Has the scope of the project changed?
- What technologies have you decided to use?
- 

Second group: BB-CLI
- How is it to work with BB?
- How will this project be deployed?

Third group: Machine learning for prevention of excavation damage
- Are there useful similarities with previous research?
- Are there any issues using the test dataset, do you think the result will differ when using the real dataset?
- How big is the test set compared to the real one?
- Do you focus on the research or the development?

Fourth group: Local learning rules for image compression
- Speed difference between multicore CPU and GPU
- How does the algorithm scale between availible cores?
- Have you tried to use it for image compression?

Specific questions for our group: Group five: ATEA
- How is the transition from java to .NET and C#
- How closely are you working with ATEA? Did they have a specific vision for the application, or have you made it, did they have technology requirements?
- How did sprints go when we had two courses? How many sprints have you gone through?
- What are the biggest unforeseen challenges so far?

Group six: Triona: Using Machine Learning to Detect Road Signs in Images and LIDAR
- DUNOO
